#ifndef NAVIAOPENEXAMPLE_CONFIG_H
#define NAVIAOPENEXAMPLE_CONFIG_H

#define NAVIA_CORE_SSID "Navia Core x"
#define NAVIA_CORE_PASS "password"
#define NAVIA_CORE_ADDR "192.168.43.1"

#endif // NAVIAOPENEXAMPLE_CONFIG_H
